// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from ../../gir-files
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal, clippy::upper_case_acronyms)]
#![cfg_attr(docsrs, feature(doc_cfg))]

use glib_sys as glib;
use gobject_sys as gobject;
use gdk4_sys as gdk;
use gtk4_sys as gtk;

#[allow(unused_imports)]
use std::ffi::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong, c_void};
#[allow(unused_imports)]
use libc::{size_t, ssize_t, time_t, off_t, intptr_t, uintptr_t, FILE};
#[cfg(unix)]
#[allow(unused_imports)]
use libc::{dev_t, gid_t, pid_t, socklen_t, uid_t};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Constants
pub const CASILDA_MAJOR_VERSION: c_int = 1;
pub const CASILDA_MICRO_VERSION: c_int = 0;
pub const CASILDA_MINOR_VERSION: c_int = 0;
pub const CASILDA_VERSION_S: &[u8] = b"1.0.0\0";

// Records
#[derive(Copy, Clone)]
#[repr(C)]
pub struct CasildaCompositorClass {
    pub parent_class: gtk::GtkWidgetClass,
}

impl ::std::fmt::Debug for CasildaCompositorClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("CasildaCompositorClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .finish()
    }
}

// Classes
#[repr(C)]
#[allow(dead_code)]
pub struct CasildaCompositor {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for CasildaCompositor {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("CasildaCompositor @ {self:p}"))
         .finish()
    }
}

extern "C" {

    //=========================================================================
    // CasildaCompositor
    //=========================================================================
    pub fn casilda_compositor_get_type() -> GType;
    pub fn casilda_compositor_new(socket: *const c_char) -> *mut CasildaCompositor;
    pub fn casilda_compositor_get_client_socket_fd(compositor: *mut CasildaCompositor) -> c_int;
    pub fn casilda_compositor_set_scrollable(compositor: *mut CasildaCompositor, scrollable: gboolean);
    pub fn casilda_compositor_spawn_async(compositor: *mut CasildaCompositor, working_directory: *const c_char, argv: *mut *mut c_char, envp: *mut *mut c_char, flags: glib::GSpawnFlags, child_setup: glib::GSpawnChildSetupFunc, user_data: gpointer, child_pid: *mut glib::GPid, error: *mut *mut glib::GError) -> gboolean;

}
