// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "CasildaCompositorClass", sizeof(CasildaCompositorClass), alignof(CasildaCompositorClass));
    return 0;
}
