// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "CasildaCompositor")]
    pub struct Compositor(Object<ffi::CasildaCompositor, ffi::CasildaCompositorClass>);

    match fn {
        type_ => || ffi::casilda_compositor_get_type(),
    }
}

impl Compositor {
    #[doc(alias = "casilda_compositor_new")]
    pub fn new(socket: &str) -> Compositor {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::casilda_compositor_new(socket.to_glib_none().0))
        }
    }

    #[doc(alias = "casilda_compositor_get_client_socket_fd")]
    #[doc(alias = "get_client_socket_fd")]
    pub fn client_socket_fd(&self) -> i32 {
        unsafe {
            ffi::casilda_compositor_get_client_socket_fd(self.to_glib_none().0)
        }
    }

    #[doc(alias = "casilda_compositor_set_scrollable")]
    pub fn set_scrollable(&self, scrollable: bool) {
        unsafe {
            ffi::casilda_compositor_set_scrollable(self.to_glib_none().0, scrollable.into_glib());
        }
    }

    //#[doc(alias = "casilda_compositor_spawn_async")]
    //pub fn spawn_async(&self, working_directory: Option<impl AsRef<std::path::Path>>, argv: &[&std::path::Path], envp: &[&std::path::Path], flags: /*Ignored*/glib::SpawnFlags, child_setup: Option<Box_<dyn FnOnce() + 'static>>, error: /*Ignored*/Option<glib::Error>) -> Result<(/*Ignored*/glib::Pid), glib::Error> {
    //    unsafe { TODO: call ffi:casilda_compositor_spawn_async() }
    //}

    pub fn socket(&self) -> Option<glib::GString> {
        ObjectExt::property(self, "socket")
    }
}
