// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/local/share/gir-1.0
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

mod compositor;
pub use self::compositor::Compositor;

pub(crate) mod builders {
    pub use super::compositor::CompositorBuilder;
}
